import "./horas.js";
import "./instructores.js";
import "./tags.js";
import "./slider.js";
import "./contadorAnimado.js";
import "./botonHamburguesa.js";
import "./mapa.js";
import "./boletosMovimiento.js";
import "./botonModoOscuro.js";
